"""Changes to Show model

Revision ID: 0fd5a2db92df
Revises: a857227d4e5a
Create Date: 2020-06-14 20:06:13.413733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd5a2db92df'
down_revision = 'a857227d4e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.String(length='Artist.name'), nullable=False))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('Show', sa.Column('venue_name', sa.String(length='Venue.name'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'start_time')
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###
