"""model fixes

Revision ID: 3cc28e7d0475
Revises: f3f35966abb7
Create Date: 2020-06-15 00:38:20.945692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cc28e7d0475'
down_revision = 'f3f35966abb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Show', 'date')
    op.drop_column('Show', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
