"""sync head; model fixes to artist & show

Revision ID: f3f35966abb7
Revises: 1e2745fdd0b7
Create Date: 2020-06-14 20:59:42.690076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f35966abb7'
down_revision = '1e2745fdd0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('Show', sa.Column('venue_name', sa.String(length='Venue.name'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
